version: '3.4'
services:
  db:
    image: raelvieira/mysql-rest-api-collaborator
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: collaborators
    ports:
      - "3308:3306"
    networks:
      - israel-network
  rest-api-collaborator:
    image: raelvieira/rest-api-collaborator
    restart: always
    build: ./backend
    working_dir: /backend
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./backend:/backend
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - israel-network
networks:
    israel-network:
        driver: bridge