CREATE TABLE IF NOT EXISTS user(
    id  INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    CONSTRAINT pk_id_user PRIMARY KEY (id)
)engine=InnoDB DEFAULT CHARSET=utf8;